### ISSUE TITLE
Using Tools page: relevant content (links) gets pushed too far down

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Pattern-Library#110]
Seen on https://iatistandard.org/en/using-data/iati-tools-and-resources/

As per screenshot (page is zoomed out)

<img width="871" alt="Screenshot 2019-05-01 at 3 22 40 pm" src="https://user-images.githubusercontent.com/1381563/57022453-1c8c6c80-6c27-11e9-8e8a-eb2cbcf68c00.png">

The boxes should live right beneath the text, since ultimately they are the relevant content of the page. Instead, the left hand navigation pushes them down near the footer. We'll have to work out a sensible way to fix this. Possibly, including the boxes inside the same grid layout the text lives in should do it.

**Comment by sargentfrancesca** [comment]
Worth noting that the screenshot above is from the [iatistandard.org website](https://iatistandard.org/en/using-data/iati-tools-and-resources/), which takes markup and styles from this pattern library.

The live implementation of tools and resources seems to be a mashup of http://styles.iatistandard.org/page-templates/01-about and http://styles.iatistandard.org/page-templates/08-1-tools-resources - a requirement for a sidebar within the tools and resources page has emerged since the design of the pattern library.
