### ISSUE TITLE
T10 Search template

### ISSUE THREAD

**Issue by benjamincoleman** [IATI/IATI-Pattern-Library#113]
Sketch: https://marvelapp.com/4cfjg52/screen/64592626

For each results we have: 

- Title
- Date - for events, news etc. that are chronological, so some with, some without
- Content snippet
- Type of content
- Highlighted terms 

We have implemented something very similar on previous Wagtail builds like GNR, including some clever work around how you weight the results to improve how it works too. 

http://gnr.surge.sh/page-templates/10-site-search-results

An example: https://globalnutritionreport.org/search/?s=health

**Comment by BenDarby** [comment]
Pattern library link: http://iati.surge.sh/page-templates/10-search

**Comment by benjamincoleman** [comment]
@BenDarby changes: 

- [ ] the highlights could do with not being green - seems to harmonious with the tabs. 

<img width="773" alt="Screen Shot 2019-09-03 at 14 11 47" src="https://user-images.githubusercontent.com/64877/64176216-d9e8d400-ce54-11e9-8365-038f5c4b875c.png">

**Comment by benjamincoleman** [comment]
@BenDarby changes to this design: http://iati.surge.sh/page-templates/10-search

Type tab too much like a button - try another style combined with the date. So we'd have: 

`BLOG : 28 OCT 2017`

On the design in general, we already have some search elements: http://iati.surge.sh/page-templates/02-6-knowledgebase-search-results and there should be a search box in the content as in the sketch. https://marvelapp.com/4cfjg52/screen/59543937. 

I would move the "Showing 10 of 56 results" out of the hero to above the results, and keep the hero super minimal. Then the search box. Something like this: 

<img width="1440" alt="Screen Shot 2019-09-05 at 14 12 53" src="https://user-images.githubusercontent.com/64877/64344909-485d9b80-cfe7-11e9-9f56-6c4fa4f3543b.png">

**Comment by benjamincoleman** [comment]
I have done this now

**Comment by urlsangel** [comment]
@benjamincoleman @samuele-mattiuzzo @BenDarby @Ocre42 

The new pattern library template for the search listings has a page type label under the title of each item:

![Screenshot 2019-11-15 at 14 23 00](https://user-images.githubusercontent.com/560463/68950139-77e10f00-07b3-11ea-9d12-e628ce893149.png)

![Screenshot 2019-11-15 at 14 23 05](https://user-images.githubusercontent.com/560463/68950141-7879a580-07b3-11ea-97e7-0eb98067437d.png)

There's a couple of inconsistencies here to note:

- Some items have "page" after the type, some don't - e.g. "Guidance page" vs "Event"
- There's a "Blog" reference, which in the site I think is "News"

In the search view, there is a list of `searchable_models`:

- AboutPage
- AboutSubPage
- CaseStudyPage
- HistoryPage,
- PeoplePage
- ContactPage
- EventPage
- GuidanceAndSupportPage,
- GuidanceGroupPage
- GuidancePage
- KnowledgebasePage
- NewsPage,
- StandardPage
- IATIStandardPage 

The current implementation will display the model's verbose name with "page" removed, so for example "GuidanceAndSupportPage" will display as "Guidance and support".

This can be overridden at the specific page model, so could someone please let me know what any overrides should be?

For example, I'm guessing that "AboutSubPage" shouldn't display as "About sub".

**Comment by benjamincoleman** [comment]
@BenDarby can you replace the "type" of result with the URL please? 

Be good if you can use real ones, and I think they'll need to move to being lower case for legibility. 

Where there's a date, let's make that a new line and introduce it. By that I mean if it's a published date, then lets have: 

PUBLISHED: DD/MM/YYYY

If it's an event, let's have: 

DATE: DD/MM/YYYY

**Comment by urlsangel** [comment]
@BenDarby 

I've had a fiddle, and this is what my template looks like locally at the moment:

![Screenshot 2019-11-26 at 14 04 40](https://user-images.githubusercontent.com/560463/69640155-cca74400-1055-11ea-9809-74923e5264d7.png)

I'll see if I can get you a dev preview this afternoon.

**Comment by BenDarby** [comment]
Updated pushed to branch

**Comment by urlsangel** [comment]
There's a few issues with this template that go beyond the scope of the original task, which was to implement better search results.

I'm noting them here for future sprints (and also for deployment of this update).

### Deployment notes

When deployed live, it will need to be in two pushes due to a previous database modification: https://github.com/IATI/IATI-Standard-Website/blob/master/search/migrations/0001_initial.py#L11

This database table deletion meant that implementing the `searchpromotions` module failed at migration time, as it expects the legacy db table to exist.

This is fixed by recreating the original `search` migration to create the table, but this needs to occur before the `searchpromotions` module is enabled and migrations run.

In essence, this line needs commenting out before the first deploy, and then uncommenting and redeploying: https://github.com/IATI/IATI-Standard-Website/blob/feature/elasticsearch/iati/settings/base.py#L71

This will ensure that the table exists before the second migration is run.

### Architecture

#### Elasticsearch

Elasticsearch has been added to the local `docker-compose` environment as version `2`, and on the server as`2.3.5`. 

The version of Wagtail that the site is currently on is `2.0.1`, which only supports Elasticsearch versions `2` and `5`. 

The Elasticsearch Dokku plugin doesn't support version `5`, so that means version `2` is the only valid option for all environments.

#### Pattern library 

The pattern library has been included as a git submodule, as there is a requirement for multiple branches to continue to exist whilst development is ongoing. This would not be possible if the raw files were copied into the main site repo.

Once development has been aligned, I would recommend that the master branch files _are_ copied over, and the PL repo left as a historical artefact.

When using the PL as a submodule, it is necessary to update to the required commit whenever new changes need to be pulled through.

#### Dokku and git submodules

As the pattern llibrary repo is separate from the site repo, Dokku needs to clone the files on deployment.

It would be expected to do this post build trigger, but actually does so as the very first task. This renders these plugins unworkable:

- https://github.com/cedricziel/dokku-hostkeys-plugin
- https://github.com/cedricziel/dokku-deployment-keys

It may be that later versions of Dokku resolve this issue.

To allow the build of the submodule, the above functionality has been added to the Dokku user itself - a private/public SSH key has been generated, with the [public key added to Github](https://github.com/IATI/IATI-Pattern-Library/settings/keys), and a `known_hosts` file initialised for the Dokku user to recognise Github.

This configuration should work for all of the apps - `dev`, `staging`, and `www` - as this transaction takes place at the Dokku level rather than the app level.

#### Search as view

The current search implementation is as a Django `view`. 

This has a few issues that require attention:

- The view does not react to the native Wagtail `privacy` settings, so is available to view even if the site is password or login protected (such as on the `dev` and `staging` servers)
- As the view is not a Wagtail `Page`, it does not display the site name as part of the `<title>` in the `<head>` (as the required function isn't a method on the view)
- It does not display the language picker in the nav, again likely because it does not have the same methods as subclassed Wagtail `Page`

#### Untranslated text in the search template

There are a number of items in the search template that do not have translation applied, such as the input label "Search the site", the button text "Search", and the results text such as "Showing 1–1 of 1 results".

**Comment by urlsangel** [comment]
### Search highlighting and punctuation variations

After internal review this week, a test search query showed inconsistency with search highlighting.

The query was: https://dev.iatistandard.org/en/search/?query=members%27+assembly

![Screenshot 2019-11-28 at 10 00 57](https://user-images.githubusercontent.com/560463/69796476-0008e080-11c6-11ea-84ac-6db36c8ff449.png)

The screenshot above shows that not all instances of "members' assembly" are highlighted in the  title or excerpt of the returned results.

This is a result of punctuation variation within the content. In this query and the first two results we have three variations of an apostrophe:

* apostrophe, or straight quote: '
* right angled quote: ’
* html entity reference for apostrophe: &#x27

I'll explain a little about what's going on, and what the options are.

#### Search vs highlighting

To clarify, there are two separate processes occurring for the results. 

The first is the search query itself, which uses the powerful [Elasticsearch](https://www.elastic.co/products/elasticsearch) backend to return relevant results. Elasticsearch gracefully handles punctation variation as detailed above - it will return the same results irrespective of whether a literal apostrophe, the html character entity, or a right angled quote was used.

The second is the highlighting function. This uses the [Haystack Highlighter](https://django-haystack.readthedocs.io/en/master/highlighting.html) to find and highlight the most relevant text found in the results. This compares text literally, without gracefully dealing with punctuation variation - hence only exact matches are highlighted.

### Options available

#### Option 1: do nothing

An argument could be made that most visitors would search for "members assembly" with no apostrophe - this would return the same results and much better highlighting:

https://dev.iatistandard.org/en/search/?query=members+assembly

![Screenshot 2019-11-28 at 10 34 20](https://user-images.githubusercontent.com/560463/69799180-abb42f80-11ca-11ea-914b-84a63849665e.png)

In this case, doing nothing is a good value option, as most results will highlight well and be unaffected if no punctation is in the search query, or if there are variations in the content.

#### Option 2: strip punctuation from the query

This could be done at query level, and should return the same results as if any query punctuation was still present. 

It would fix the highlighting issue in the same way as the example above, where non-punctuation words would be highlighted if present in the content and search term.

This option would take up to an hour to implement and test.

#### Option 3: develop the highlighter further to normalise punctuation variation

As well as apostrophes, there are other punctuation marks that can come in different forms -[ see this page for examples of common entities](https://www.toptal.com/designers/htmlarrows/punctuation/).

The highlighter could be extended to match these variations and highlight as intuitively expected, but it's a non-trivial task. 

I'd estimate from a few hours to a day or two develop and test a solution like this.

**Comment by urlsangel** [comment]
### Normalised search highlighting

The search highlight function has now been updated to normalise punctuation variation for better highlighting.

The initial pass at this used the [Unidecode](https://pypi.org/project/Unidecode/) library to normalise variations such as curly quotes or apostrophes to their plain ASCII equivalent. This caused issues, however, as some single unicode characters (such as the one below) would be converted to two or more equivalent characters, in this case two commas:

- "Double low-9 quotation mark": „  
- Converted to: ,,

This caused issues with highlighting, as the original text character count now differed from the normalised text.

The current implementation now normalises manually, with a map of quotation variations and their preferred ASCII single character equivalent:

```
MAP = {
    '"': '«|»|“|”|„|‟|″|‴|⁗|‶|‷',
    "'": '‘|’|‚|‛|′|‵|‹|›',
    '‐': '‑|‒|-|—|―',
    '*': '⁎',
}
```

These punctuation marks are referenced from here: https://www.toptal.com/designers/htmlarrows/punctuation/

To clarify, any character that matches any in the lists on the right are replaced for comparison purposes by its ASCII equivalent on the left. The original text is unchanged, as we are just looking for the character index numbers to place the highlight CSS in the correct place.

The user does not see any difference in their original search query, or the original text of the search result items.

#### Amending the punctuation map

This is a best guess of the punctuation that makes sense to normalise - it's simple to amend if it needs tweaking/adding to.

**Comment by benjamincoleman** [comment]
@BenDarby can you add a sentence under the number of results reading: 

> Results are ordered by relevance.

It should be fairly unobtrusive, and it would be an idea to put in a horizontal line underneath to separate it out from the results. 

I've update the sketch: https://marvelapp.com/4cfjg52/screen/64592626
